### ISSUE TITLE
Wrong path for installing pip3 requirements

### ISSUE THREAD

**Issue by UserRS232** [hvoerman/solis2mqtt#2]
... same issue as with incub. Just copy/paste

I have just a litte improvement, what caused an Error during Installation:

From the documentation, setup.sh is intended to be run like "sudo bash /opt/solis2mqtt/setup.sh".
That way, pip3 can not load the requirements.txt from the opt folder, since the working directory is still different.

echo "### Installing requirements ###"
pip3 install -r requirements.txt

needs to be changed to:

echo "### Installing requirements ###"
pip3 install -r /opt/solis2mqtt/requirements.txt

**Comment by hvoerman** [comment]
Thanks for this input. I fixed it.
