### ISSUE TITLE
Fresh install on Debian 11 x86 and I have a syntax error

### ISSUE THREAD

**Issue by realist625** [hvoerman/solis2mqtt#4]
On a fresh install of Debian 11 I can’t get this software to run.  It is like to be a simple issue, but I don’t know how to fix it.
I get the following error:

  File "./solis2mqtt.py", line 30
    self.register_cfg = ...
                        ^
SyntaxError: invalid syntax

I am not sure why that is the case.    I also observed that the pushd / popd in the setup.sh had ‘/opt/solismqtt’ as a directory rather that ‘/opt/solis2mqqt’.    I think it will run ok anyway, but it still generates errors .

**Comment by hvoerman** [comment]
What version of Python are you using. I use, and I think I do not mention that in the docs, python 3.9.2 on my RPI. Python version 2 won't work I think.

The pushd/popd issue is known. Feel free to fix it ;-)

**Comment by realist625** [comment]
I am not sure what was wrong, could not explain it or figure it out.   What I ended up doing was to start again, then it sort of worked with all the bits installed. I am able to run the code at least.

I still have massive issues getting anything useful from the inverter, but I will log that separately.  

Thanks.
